package common.kodehawa.ce.main;

import java.util.Arrays;
import java.util.logging.Level;

import javax.annotation.processing.SupportedSourceVersion;
import javax.lang.model.SourceVersion;

import net.minecraft.client.Minecraft;
import net.minecraft.command.ICommandManager;
import net.minecraft.command.ServerCommandManager;
import net.minecraft.server.MinecraftServer;
import net.minecraftforge.common.MinecraftForge;
import common.kodehawa.ce.commands.*;
import common.kodehawa.ce.logger.DynamicLogger;
import common.kodehawa.ce.module.man.ModuleManager;
import common.kodehawa.ce.tick.TickHandler;
import common.kodehawa.ce.util.CEInitializationError;
import common.kodehawa.ce.util.ConfigManager;
import common.kodehawa.ce.util.CrashManager;
import common.kodehawa.ce.util.ForgeEvents;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.event.FMLServerStartingEvent;
import cpw.mods.fml.common.registry.TickRegistry;
import cpw.mods.fml.relauncher.Side;

@SupportedSourceVersion(SourceVersion.RELEASE_6)
@Mod(modid="Cheating-Essentials", name="Cheating Essentials Reloaded", version="4.0.0")
public class CheatingEssentials {

	@Instance("Cheating-Essentials")
	public static CheatingEssentials main;
	TickHandler tickhandler = new TickHandler();
	
	@EventHandler
	public void preInitialization(FMLPreInitializationEvent e){
		DynamicLogger.instance().writeLog("Loading Cheating Essentials "+modVersion+" in " + MinecraftForge.getBrandingVersion(), Level.INFO);
		MinecraftForge.EVENT_BUS.register(new ForgeEvents());

		Minecraft.getMinecraft().mcProfiler.startSection("Cheating Essentials Starting");
		/* Cheating Essentials MD START */
		ModMetadata mMetadata = e.getModMetadata();
		mMetadata.credits = "Kodehawa";
		mMetadata.description = "The most complete Forge cheating mod, with a lot of options and configurable cheats!";
		mMetadata.autogenerated = false;
		mMetadata.version = this.modVersion;
		mMetadata.authorList = Arrays.asList(new String[] { "Kodehawa" });
		mMetadata.url = "http://www.minecraftforum.net/topic/1846289-";
		/* Cheating Essentials MD FINISH */
	}
	
	@EventHandler
	public void initialization(FMLInitializationEvent e){
		TickRegistry.registerScheduledTickHandler(tickhandler, Side.CLIENT);
		try{
			load();
		}
		catch(CEInitializationError error){
			CrashManager.instance().propagate("Error on Cheating Essentials Instance Loading", error);
		}
	}
	
	@EventHandler
	public void postInitialization(FMLPostInitializationEvent e){
		Minecraft.getMinecraft().mcProfiler.startSection("Cheating Essentials Start");
		DynamicLogger.instance().writeLog("Cheating Essentials v4 succefully started in Minecraft 1.6.4", Level.INFO);
	}
	
	@EventHandler
	public void serverStarting(FMLServerStartingEvent ev){
		/* COMMAND REGISTERER START */
		MinecraftServer server = MinecraftServer.getServer();
		ICommandManager icommand = server.getCommandManager();
		ServerCommandManager command = ((ServerCommandManager) icommand);
		command.registerCommand(new CommandModuleList());
		command.registerCommand(new CommandModuleToggle());
		command.registerCommand(new CommandSMKeybind());
		command.registerCommand(new CommandAddFriend());
		command.registerCommand(new CommandAddEnemy());
		command.registerCommand(new CommandFlySpeed());
		command.registerCommand(new CommandStepHeight());
		/* COMMAND REGISTERER FINISH */
		
	}
	
	private void load() throws CEInitializationError {
		ModuleManager.instance();
		ConfigManager.instance();
	}
	
	static String majorVersion = "4";
	static String minorVersion = "0";
	static String revision = "0";
	static String status = "Pre-Alpha";
	public final String modVersion = majorVersion+"."+minorVersion+"."+revision+" "+status;
}
