package common.kodehawa.ce.main;

import java.util.Arrays;
import java.util.logging.Level;

import net.minecraftforge.client.event.RenderWorldLastEvent;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.event.ForgeSubscribe;

import common.kodehawa.ce.logger.DynamicLogger;
import common.kodehawa.ce.module.core.ModuleAbstract;
import common.kodehawa.ce.module.man.ModuleManager;
import common.kodehawa.ce.tick.TickHandler;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.registry.TickRegistry;
import cpw.mods.fml.relauncher.Side;

@Mod(modid="Cheating-Essentials", name="Cheating Essentials Reloaded", version="4.0.0")
public class CheatingEssentials {

	@Instance("Cheating-Essentials")
	public static CheatingEssentials main;
	
	@EventHandler
	public void preInitialization(FMLPreInitializationEvent e){
		DynamicLogger.instance().writeLog("Loading Cheating Essentials "+modVersion+" in " + MinecraftForge.getBrandingVersion(), Level.INFO);
		/* Cheating Essentials MD START */
		ModMetadata mMetadata = e.getModMetadata();
		mMetadata.credits = "Kodehawa";
		mMetadata.description = "The most complete Forge cheating mod, with a lot of options and configurable cheats!";
		mMetadata.autogenerated = false;
		mMetadata.version = this.modVersion;
		mMetadata.authorList = Arrays.asList(new String[] { "Kodehawa" });
		mMetadata.url = "http://www.minecraftforum.net/topic/1846289-";
		/* Cheating Essentials MD FINISH */
	}
	
	@EventHandler
	public void initialization(FMLInitializationEvent e){
		TickHandler tickhandler = new TickHandler();
		MinecraftForge.EVENT_BUS.register(this);
		TickRegistry.registerScheduledTickHandler(tickhandler, Side.CLIENT);
		loadClasses();
	}
	
	@EventHandler
	public void postInitialization(FMLPostInitializationEvent e){
		DynamicLogger.instance().writeLog("Cheating Essentials v4 succefully started in Minecraft 1.6.4", Level.INFO);
	}
	
	@ForgeSubscribe
	public void worldTick(RenderWorldLastEvent e){
		for(ModuleAbstract module : ModuleManager.instance().avModules){
			module.doRender();
		}
	}
	
	void loadClasses(){
		ModuleManager.instance();
	}
	
	static String majorVersion = "4";
	static String minorVersion = "0";
	static String revision = "0";
	static String status = "Pre-Alpha";
	public final String modVersion = majorVersion+"."+minorVersion+"."+revision+" "+status;
}
